apiVersion: v1
kind: Service
metadata:
  labels:
    app: termination-tickets-web-service-web
  name: web
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 31080
  selector:
    app: termination-tickets-web-service-web
  type: NodePort
