apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: termination-tickets-web-service-web
  name: termination-tickets-web-service-web
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: termination-tickets-web-service-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: termination-tickets-web-service-web
    spec:
      containers:
      - image: termination-tickets:1.0
        imagePullPolicy: IfNotPresent
        name: termination-tickets
        command:
          - python
          - main.py
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: code
            mountPath: /app
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: code
          hostPath:
            path: /mount-termination-tickets
            type: Directory
