apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: termination-tickets-web-service-worker
  name: termination-tickets-web-service-worker
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: termination-tickets-web-service-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: termination-tickets-web-service-worker
    spec:
      containers:
      - image: termination-tickets:1.0
        imagePullPolicy: IfNotPresent
        name: termination-tickets
        command:
          - python
          - worker.py
        volumeMounts:
          - name: code
            mountPath: /app
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: code
          hostPath:
            path: /mount-termination-tickets
            type: Directory